Dataset:
    name           : 'my_data'
    basepath       : '/path/to/my/data/folders'
    data_shape     : !!python/tuple [160, 480, 480]
    dim_resolution : !!python/tuple [2., .65, .65]
    marker_columns : !!python/tuple [' z', ' y', '#x']

Experiment:
    name           : 'my_exp'
    basepath       : '/path/to/my/experiment/outputs'

PreProcessing:
    transpose         : !!python/tuple [2, 1, 0]
    flip_axis         : 1
    clip_threshold    : 8192
    gamma_correction  : 1.2
    downscale         : null
    normalization     : 'input'
    standardization   : null

DataAugmentation:
    augment      : true
    gamma        : !!python/tuple [0.5, 1.8]
    contrast     : null
    brightness   : !!python/tuple [-0.1, 0.1]
    zoom         : !!python/tuple [1.0, 1.3]
    gauss_filter : !!python/tuple [0.5, 2]
    noise        : !!python/tuple [0.05, 0.15]

UNet:
    val_fold       : '1/4'
    val_seed       : 123
    input_shape    : !!python/tuple [240, 240, 80]
    exclude_border : !!python/tuple [10, 10, 3]
    epochs         : 3000
    batch_size     : 10
    learning_rate  : 0.001
    n_filters      : 32
    k_size         : !!python/tuple [5, 5, 3]
    k_stride       : !!python/tuple [2, 2, 2]

DoG:
    iterations     : 40
    exclude_border : !!python/tuple [10, 10, 3]
    max_match_dist : 10
    n_cpu          : 1

VirtualFusedVolume:
    name           : 'vfv_name'
    config_file    : '/path/to/vfv/stitch.yml'
    sub_shape      : !!python/tuple [160, 480, 480]
    sub_overlap    : !!python/tuple [8, 20, 20]
    mask_path      : '/path/to/mask.tiff'
    mask_downscale : !!python/tuple [3, 3, 3]
    outdir         : '/path/to/vfv/predictions/folder'
