Dataset:
    name           : 'my_data'
    basepath       : '/path/to/my/data/folders'
    shape          : [160, 480, 480]
    dim_resolution : [2., .65, .65]
    marker_columns : [' z', ' y', '#x']

Experiment:
    name           : 'my_exp'
    basepath       : '/path/to/my/experiment/outputs'

PreProcessing:
    transpose         : [2, 1, 0]
    flip_axis         : 1
    clip_threshold    : 8192
    gamma_correction  : 1.2
    downscale         : null
    normalization     : 'input'
    standardization   : null

DataAugmentation:
    augment: true
    gamma: 
        param_range     : [0.8, 1.2]
        p               : 0.3
    # contrast: 
    #     param_range     : [1., 3.]
    brightness: 
        param_range     : [-0.06, 0.06]
        p               : 0.3
    # zoom: 
    #     param_range     : [1.0, 1.1]
    #     order           : 1
    #     p               : 0.3
    blur:
        param_range     : [0., 0.5]
        p               : 0.3
    noise:
        param_range     : [0., 0.03]
        p               : 0.3
    # rotation:
    #     param_range     : [0., 270.]
    #     axes            : [-2, -1]
    #     p               : 0.3
    flip:
        axes            : [-2]
        p               : 0.3

UNet:
    val_fold       : '1/4'
    val_seed       : 123
    input_shape    : [240, 240, 80]
    exclude_border : [10, 10, 3]
    epochs         : 3000
    batch_size     : 10
    learning_rate  : 0.001
    n_filters      : 32
    k_size         : [5, 5, 3]
    k_stride       : [2, 2, 2]
    dropout        : null
    regularizer    : tf.keras.regularizers.L1(0.003)

DoG:
    iterations     : 40
    exclude_border : [10, 10, 3]
    max_match_dist : 10
    n_cpu          : 1

VirtualFusedVolume:
    name           : 'vfv_name'
    config_file    : '/path/to/vfv/stitch.yml'
    sub_shape      : [160, 480, 480]
    sub_overlap    : [8, 20, 20]
    mask_path      : '/path/to/mask.tiff'
    mask_downscale : [3, 3, 3]
    outdir         : '/path/to/vfv/predictions/folder'
