Dataset:
    name           : my_data
    basepath       : /path/to/my/data/folders
    shape          : [160, 480, 480]
    dim_resolution : [2., .65, .65]
    marker_columns : [' z', ' y', '#x']

Experiment:
    name           : my_exp
    basepath       : /path/to/my/experiment/outputs

PreProcessing:
    flip_axis         : 1
    clip_threshold    : 8192
    gamma_correction  : 1.2
    downscale         : null
    normalization     : 'input'
    standardization   : null

DataAugmentation:
    augment: true
    gamma: 
        param_range     : [0.8, 1.2]
        p               : 0.3
    # contrast: 
    #     param_range     : [1., 3.]
    #     p               : 0.3
    brightness: 
        param_range     : [-0.06, 0.06]
        p               : 0.3
    # zoom: 
    #     param_range     : [1.0, 1.1]
    #     order           : 1
    #     p               : 0.3
    blur:
        param_range     : [0., 0.5]
        p               : 0.3
    noise:
        param_range     : [0., 0.03]
        p               : 0.3
    # rotation:
    #     param_range     : [0., 270.]
    #     axes            : [-2, -1]
    #     p               : 0.3
    flip:
        axes            : [-2]
        p               : 0.3

UNet:
    input_shape    : [80, 240, 240]
    exclude_border : [3, 10, 10]
    epochs         : 1500
    batch_size     : 4
    learning_rate  : 0.001
    add_dice       : False
    n_filters      : 32
    k_size         : [3, 5, 5]
    k_stride       : [2, 2, 2]
    dropout        : null
    regularizer    : null

DoG:
    iterations     : 40
    exclude_border : [3, 10, 10]
    max_match_dist : 10
    n_cpu          : 1

VirtualFusedVolume:
    name           : 'vfv_name'
    config_file    : '/path/to/vfv/stitch.yml'
    sub_shape      : [160, 480, 480]
    sub_overlap    : [8, 20, 20]
    mask_path      : '/path/to/mask.tiff'
    mask_downscale : [3, 3, 3]
    outdir         : '/path/to/vfv/predictions/folder'
