Experiment:
    name           : 'tomato_030323'
    basepath       : '/mnt/NASone/ludo/cfos/neuralnet/training_tomato_030323/experiments'

VirtualFusedVolume:
    name             : 'vfv_name'
    config_file      : '/path/to/vfv/stitch.yml'
    dim_resolution   : [2., .65, .65]
    patch_shape      : [160, 480, 480]
    patch_overlap    : [12, 36, 36]  # NOTE: it should be at least two times the diameter of the largest cell
    mask_path        : '/path/to/mask.tiff'
    outdir           : '/path/to/vfv/predictions/folder'


# Attn! Should be identical to the training phase! Be aware of any differences: check training config file!
PreProcessing:
    clip         : 'bit'  # can be one of ['constant', 'bit', 'quantile', 'auto', 'none', null]
    clip_value   : 14
    center       : null  # can be one of ['constant', 'min', 'mean', 'none', null]
    center_value : null
    scale        : 'bit'  # can be one of ['constant', 'bit', 'max', 'std', 'none', null]
    scale_value  : 14

